# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^(.+\.svg)$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [ '--maxkb=100000' ]
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-byte-order-marker  # Forbid UTF-8 byte-order markers

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.2
    hooks:
      - id: ruff  # Run the linter.
        args: [ --select, I, --fix ]
      - id: ruff-format  # Run the formatter.
